site_name: bulletin_board
site_description: API for bulletin board
repo_url: https://github.com/nikkomidoy/bulletin-board-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/nikkomidoy">nikkomidoy</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Boards: 'api/boards.md'
    - Threads: 'api/threads.md'
    - Posts: 'api/posts.md'
